import { getDb, ensureTables } from '../db';
import { NextResponse } from 'next/server';

const SEED_MEMBERS = [
  { f:'Stan', l:'Abramski', e:'jabramski1442@gmail.com', p:'' },
  { f:'Larry', l:'Anderson', e:'lfandersonjr@gmail.com', p:'2026-01-01' },
  { f:'Neil', l:'Anderson', e:'ZNAnderson@yahoo.com', p:'' },
  { f:'James', l:'Apple', e:'japple2665@aol.com', p:'2026-01-01' },
  { f:'Elias', l:'Ashey', e:'eliasashey648@gmail.com', p:'' },
  { f:'Issam', l:'Attari', e:'attari.issam@gmail.com', p:'' },
  { f:'Ed', l:'Bass', e:'edbass1938@gmail.com', p:'' },
  { f:'Edgardo', l:'Bianchi', e:'ebianchi40@yahoo.com', p:'' },
  { f:'Charlie', l:'Bowen', e:'charliebowen13@gmail.com', p:'' },
  { f:'Bruce', l:'Bowker', e:'ebowker1@yahoo.com', p:'2026-01-01' },
  { f:'Lee', l:'Brennan', e:'LBrennan1486@gmail.com', p:'' },
  { f:'Phillip', l:'Brown', e:'p2227696@yahoo.com', p:'' },
  { f:'Jim', l:'Brumit', e:'jimbrumit@aol.com', p:'' },
  { f:'William', l:'Bryan', e:'billbryan1946@gmail.com', p:'' },
  { f:'John', l:'Burchill', e:'burchilljohn@aol.com', p:'2026-01-01' },
  { f:'Gilbert', l:'Burnett', e:'ghenryburnett@gmail.com', p:'' },
  { f:'Tom', l:'Burrell', e:'tom.burrell@verizon.net', p:'' },
  { f:'Kevin', l:'Casey', e:'kcasey145@hotmail.com', p:'' },
  { f:'George', l:'Casola', e:'georgecasola@reagan.com', p:'' },
  { f:'Roger', l:'Cates', e:'rwcates@bellsouth.net', p:'' },
  { f:'Bill', l:'Chaucer', e:'chaucer1938@att.net', p:'' },
  { f:'Hennith', l:'Chestnut', e:'kschestnut@att.net', p:'' },
  { f:'Don', l:'Cole', e:'doncole1492@gmail.com', p:'2026-01-01' },
  { f:'Bill', l:'Colvin', e:'bill_colvin@msn.com', p:'' },
  { f:'Bob', l:'Corriston', e:'bmmc917@aol.com', p:'' },
  { f:'Brian', l:'Coughlan', e:'BCoughlan@UtilManagement.com', p:'' },
  { f:'Richard', l:'Cutting', e:'cutting28@sbcglobal.net', p:'' },
  { f:'Paul', l:'Czesak', e:'czesakp@aol.com', p:'' },
  { f:'Bruce', l:'Daniels', e:'danielsbruce@verizon.net', p:'2026-01-01' },
  { f:'Sam', l:'Daniluk', e:'DanilukSam09@gmail.com', p:'' },
  { f:'C. I. Pete', l:'Davis', e:'jjandbo@aol.com', p:'' },
  { f:'Jim', l:'DeFrance', e:'defrancej6@gmail.com', p:'' },
  { f:'Hema', l:'DeSilva', e:'2docs@comcast.net', p:'2026-01-01' },
  { f:'John', l:'Dethorn', e:'jacarde42@yahoo.com', p:'' },
  { f:'Robert', l:'Doleman', e:'doleman1936@hotmail.com', p:'' },
  { f:'William', l:'Drennen', e:'SBDGlade@gmail.com', p:'' },
  { f:'Gary', l:'Ebeltoft', e:'gebeltoft@ec.rr.com', p:'2026-01-01' },
  { f:'Bob', l:'Erickson', e:'bobericksonnc@gmail.com', p:'' },
  { f:'Roger', l:'Evans', e:'judyrog2@gmail.com', p:'2026-01-01' },
  { f:'Jim', l:'Fagan', e:'jfagan2012@aol.com', p:'' },
  { f:'Fred', l:'Fisher', e:'fh.fisher@charter.net', p:'' },
  { f:'Mel', l:'Foels', e:'mdfoels@yahoo.com', p:'2026-01-01' },
  { f:'Bob', l:'Foley', e:'rjfoley@ec.rr.com', p:'' },
  { f:'Charles', l:'Fox', e:'', p:'' },
  { f:'Bill', l:'Freccia', e:'WFreccia@aol.com', p:'2026-01-01' },
  { f:'Edward', l:'French', e:'tedfrench72@aol.com', p:'' },
  { f:'Bob', l:'Freund', e:'bob@TwinTack.com', p:'' },
  { f:'John', l:'Frye', e:'johncfrye@gmail.com.', p:'' },
  { f:'Myron', l:'Furman', e:'furman5004@gmail.com', p:'' },
  { f:'John', l:'Gangemi', e:'JohnGangemi@gmail.com', p:'' },
  { f:'Bob', l:'Gary', e:'BobGary96@gmail.com', p:'' },
  { f:'John', l:'Gill', e:'jag4440@yahoo.com', p:'2026-01-01' },
  { f:'Bill', l:'Guyton', e:'bguyton@gmail.com', p:'' },
  { f:'John', l:'Harmon', e:'jharmon3@earthlink.net', p:'' },
  { f:'Don', l:'Harris', e:'donharris@intracoastalrealty.com', p:'' },
  { f:'Don', l:'Hatley', e:'donhatley@ymail.com', p:'2026-01-01' },
  { f:'Fred', l:'Heaton', e:'efheaton@gmail.com', p:'' },
  { f:'Norm', l:'Heintz', e:'nheintz57@mindspring.com', p:'2026-01-01' },
  { f:'Gary', l:'Henderson', e:'surfingspeedbird@aol.com', p:'' },
  { f:'Les', l:'Hewlett', e:'ilmguy24@proton.me', p:'2026-01-01' },
  { f:'Dan', l:'Hickman', e:'danhhickman@gmail.com', p:'2026-01-01' },
  { f:'Jerry', l:'Hodnett', e:'jerryhodnett@gmail.com', p:'2026-01-01' },
  { f:'James', l:'Hogan', e:'hogan2000@mac.com', p:'' },
  { f:'Fred', l:'Holdsworth', e:'fred.holdsworth@yahoo.com', p:'' },
  { f:'Michael', l:'Hollmann', e:'dorfstr5@googlemail.com', p:'2026-01-01' },
  { f:'Dick', l:'Hull', e:'drumhill@gmail.com', p:'' },
  { f:'Dennis', l:'Hurlebaus', e:'hurlebausd@gmail.com', p:'' },
  { f:'Roger', l:'James', e:'RJQB17@aol.com', p:'' },
  { f:'Thomas', l:'Jones', e:'tjones43@ec.rr.com', p:'2026-01-01' },
  { f:'Wilbur', l:'Jones', e:'joneswd@ec.rr.com', p:'' },
  { f:'Bill', l:'Jordon', e:'bdjor@hotmail.com', p:'' },
  { f:'Robert', l:'Kaess', e:'in.kaess@gmail.com', p:'' },
  { f:'Ed', l:'Kiefhaber', e:'ekiefhaber33@gmail.com', p:'' },
  { f:'Tom', l:'Kirkpatrick', e:'kirkpatricktom100@gmail.com', p:'' },
  { f:'Larry', l:'Knott', e:'lakii@aol.com', p:'' },
  { f:'Bill', l:'Knowles', e:'billknowles3040@gmail.com', p:'' },
  { f:'Michael', l:'Kranchalk', e:'makranchalk@yahoo.com', p:'' },
  { f:'John', l:'Kristan', e:'regnjon@hotmail.com', p:'2026-01-01' },
  { f:'Dale', l:'Landon', e:'radinfla@gmail.com', p:'' },
  { f:'JP', l:'Lavoie', e:'JPLavoie@live.com', p:'' },
  { f:'Eddie', l:'Lawler', e:'elawl@aol.com', p:'' },
  { f:'Richard', l:'Lawler', e:'rlawlerpaint@yahoo.com', p:'' },
  { f:'Morris', l:'Levy', e:'melevy11@verizon.net', p:'' },
  { f:'Edward', l:'Lillis', e:'Edcycler@aim.com', p:'' },
  { f:'John', l:'Lilly', e:'jlilly1@gmail.com', p:'' },
  { f:'Kin', l:'Liversidge', e:'Kin.Liversidge@gmail.com', p:'' },
  { f:'Jack', l:'Lucas', e:'papaluke@aol.com', p:'' },
  { f:'Stephen', l:'Manning', e:'chargeon2@hotmail.com', p:'2026-01-01' },
  { f:'Joe', l:'Mason', e:'joemason776@gmail.com', p:'2026-01-01' },
  { f:'Bill', l:'Mathis', e:'wbmathis324@gmail.com', p:'2026-01-01' },
  { f:'James', l:'McCarthy', e:'Mccarthy.j.j@att.net', p:'2026-01-01' },
  { f:'Edward', l:'McCormick', e:'emmccorm1@att.net', p:'' },
  { f:'Jerry', l:'McIntosh', e:'jeamc@bellsouth.net', p:'' },
  { f:'John', l:'Melia', e:'jmelia1312@gmail.com', p:'2026-01-01' },
  { f:'Doug', l:'Miller', e:'dougmiller5108@gmail.com', p:'' },
  { f:'William', l:'Mitchell', e:'wejam11@aol.com', p:'' },
  { f:'William', l:'Mogensen', e:'mogie@alum.mit.edu', p:'' },
  { f:'James', l:'Morgan', e:'hmorgan2000@charter.net', p:'' },
  { f:'James', l:'Morrow', e:'jkmorrow1@hotmail.com', p:'2026-01-01' },
  { f:'James', l:'Mulligan', e:'geojimmulligan@gmail.com', p:'2026-01-01' },
  { f:'Gary', l:'Naylor', e:'GolfGDN@ME.com', p:'2026-01-01' },
  { f:'Floyd', l:'Nelson', e:'fjn39@ec.rr.com', p:'' },
  { f:'Jim', l:'Nelson', e:'jimn28412@gmail.com', p:'' },
  { f:'Ed', l:'Olsson', e:'olssonnc@gmail.com', p:'' },
  { f:'John', l:'Ormand', e:'jwoandbco@aol.com', p:'' },
  { f:'John', l:'Parker', e:'annandjohn341@gmail.com', p:'2026-01-01' },
  { f:'Randy', l:'Peebles', e:'randyp3@earthlink.net', p:'' },
  { f:'Seymour', l:'Pizette', e:'PizetteSeymour2@gmail.com', p:'' },
  { f:'George', l:'Plarre', e:'printsinthesand327@gmail.com', p:'' },
  { f:'Charles', l:'Plasters', e:'charlesplasters@gmail.com', p:'' },
  { f:'Richard', l:'Polomik', e:'RPolomik@aol.com', p:'' },
  { f:'Carlos', l:'Poole', e:'carlos1poole@gmail.com', p:'' },
  { f:'Edward', l:'Santucci', e:'santucci1938@yahoo.com', p:'' },
  { f:'Phillip', l:'Savonen', e:'No email', p:'' },
  { f:'Ken', l:'Schiess', e:'kschiess2018@gmail.com', p:'2026-01-01' },
  { f:'Garland', l:'Scott', e:'ges102xal@gmail.com', p:'' },
  { f:'Jim', l:'Shaughnessy', e:'JimShaughnessy1@gmail.com', p:'2026-01-01' },
  { f:'James', l:'Sieme', e:'Jhsieme45@gmail.com', p:'' },
  { f:'Brian', l:'Smith', e:'BSmith9@ec.rr.com', p:'' },
  { f:'John', l:'Spriggs', e:'JPSPRIGGS84@gmail.com', p:'2026-01-01' },
  { f:'Milton', l:'Stevenson', e:'miltystevenson@gmail.com', p:'' },
  { f:'John', l:'Stewart', e:'johnandmelindas@aol.com', p:'2026-01-01' },
  { f:'William', l:'Stokes', e:'landbstokes@gmail.com', p:'' },
  { f:'Jack', l:'Strenkowski', e:'jgstren@bellsouth.net', p:'' },
  { f:'Jim', l:'Strouse', e:'jstrouse@ec.rr.com', p:'' },
  { f:'Mark', l:'Swanstrom', e:'mswanstrom@hotmail.com', p:'' },
  { f:'George', l:'Taylor', e:'pop@nctaylors.com', p:'2026-01-01' },
  { f:'George', l:'Taylor, Jr.', e:'george@nctaylors.com', p:'' },
  { f:'Ronald', l:'Thompson', e:'ronaldt93@gmail.com', p:'' },
  { f:'Bill', l:'Toms', e:'Btoms1213@yahoo.com', p:'' },
  { f:'Derek', l:'Topham', e:'barlick@charter.net', p:'2026-01-01' },
  { f:'Emil', l:'Trabulsi', e:'et1028@yahoo.com', p:'2026-01-01' },
  { f:'Allen', l:'Van Dyke', e:'allenholsteadvandyke@gmail.com', p:'' },
  { f:'Ben', l:'Van Etten', e:'benvanet@aol.com', p:'' },
  { f:'Michael', l:'Vukelich', e:'vukelich@bellsouth.net', p:'' },
  { f:'James', l:'Wagner', e:'annwags@bellsouth.net', p:'' },
  { f:'Lawrence', l:'Ward', e:'Lewblue@yahoo.com', p:'' },
  { f:'John', l:'Watson', e:'247000jw@gmail.com', p:'' },
  { f:'Spencer', l:'Weig', e:'spencer.weig@gmail.com', p:'' },
  { f:'John', l:'Weisz', e:'hans52weisz@gmail.com', p:'2026-01-01' },
  { f:'Bob', l:'White', e:'BuilderBobinstx@hotmail.com', p:'' },
  { f:'Glenn', l:'Wilkinson', e:'glen4912000@yahoo.com', p:'' },
  { f:'Robert', l:'Wilson', e:'rwilson39@nycap.rr.com', p:'' },
  { f:'Gordon', l:'Wright', e:'Gordiepie@aol.com', p:'' },
  { f:'Walter', l:'Yates', e:'71EEHOKIE@gmail.com', p:'2026-01-01' },
  { f:'Bert', l:'Yepko', e:'bertyepko@gmail.com', p:'' },
  { f:'Paul', l:'Zambuto', e:'PZMensClub@gmail.com', p:'2026-01-01' },
  { f:'Edward', l:'Bass', e:'(no email on file)', p:'' },
  { f:'Ed', l:'Bianchi', e:'(no email on file)', p:'' },
  { f:'Phil', l:'Brown', e:'(no email on file)', p:'2026-01-01' },
  { f:'Bill', l:'Bryan', e:'(no email on file)', p:'' },
  { f:'William', l:'Chaucer', e:'(no email on file)', p:'' },
  { f:'William', l:'Chestnut', e:'(no email on file)', p:'' },
  { f:'Cl Pete', l:'Davis', e:'(no email on file)', p:'' },
  { f:'James', l:'De France', e:'(no email on file)', p:'' },
  { f:'Jack', l:'Dethorn', e:'(no email on file)', p:'' },
  { f:'Bill', l:'Drennen', e:'(no email on file)', p:'' },
  { f:'Robert', l:'Erickson', e:'(no email on file)', p:'' },
  { f:'Robert', l:'Foley', e:'(no email on file)', p:'2026-01-01' },
  { f:'Ed', l:'French', e:'(no email on file)', p:'2026-01-01' },
  { f:'E Fred', l:'Heaton', e:'(no email on file)', p:'' },
  { f:'Wilbur', l:'Jones Jr', e:'(no email on file)', p:'' },
  { f:'Bill', l:'Jordan', e:'(no email on file)', p:'2026-01-01' },
  { f:'Ed', l:'Lillis', e:'(no email on file)', p:'' },
  { f:'Jerry', l:'Mc Intosh', e:'(no email on file)', p:'' },
  { f:'Ed', l:'Mccormick', e:'(no email on file)', p:'' },
  { f:'Cy', l:'Pizette', e:'(no email on file)', p:'' },
  { f:'Ed', l:'Santucci', e:'(no email on file)', p:'' },
  { f:'Phil', l:'Savonen', e:'(no email on file)', p:'' },
  { f:'George', l:'Taylor Jr.', e:'(no email on file)', p:'2026-01-01' },
  { f:'Ron', l:'Thompson', e:'(no email on file)', p:'2026-01-01' },
  { f:'Mike', l:'Vukelich', e:'(no email on file)', p:'' },
  { f:'Jim', l:'Wagner', e:'(no email on file)', p:'' },
  { f:'Hubert', l:'Yepko', e:'(no email on file)', p:'' }
];

export async function GET() {
  try {
    const sql = getDb();
    await ensureTables(sql);
    
    // Check if already seeded
    const existing = await sql`SELECT COUNT(*) as count FROM members`;
    if (parseInt(existing[0].count) > 0) {
      return NextResponse.json({ message: `Already seeded with ${existing[0].count} members` });
    }
    
    // Insert all members
    for (const m of SEED_MEMBERS) {
      await sql`
        INSERT INTO members (first_name, last_name, email, status, join_date, last_dues_paid)
        VALUES (${m.f}, ${m.l}, ${m.e}, 'active', '2026-01-01', ${m.p || null})
      `;
    }
    
    return NextResponse.json({ message: `Seeded ${SEED_MEMBERS.length} members` });
  } catch (e) {
    return NextResponse.json({ error: e.message }, { status: 500 });
  }
}
